pipeline {
  agent any
  stages {
    stage('Build Docker Image') {
      steps {
        sh 'docker build -t abhishekf5/bp:${GIT_COMMIT} -f ProductServiceDockerfile .'
      }
    }
    stage('Push Docker Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'docker-registry-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
          sh 'docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} abhishekf5'
          sh 'docker push abhishekf5/bp:${GIT_COMMIT}'
        }
      }
    }
    stage('Deploy to Kubernetes') {
      steps {
        withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG')]) {
          sh 'kubectl --kubeconfig ${KUBECONFIG} set image deployment/bp bpe=abhishekf5/bp:${GIT_COMMIT} --record'
        }
      }
    }
  }
}
