apiVersion : apps/v1
kind: Deployment
metadata:
  name: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be
  template:
    metadata:
      labels:
        app: be
    spec:
      containers:
        - name: crystalgaobloodpressure 
          image: aksdevopsacrbp1353.azurecr.io/crystalgaobloodpressurebe:37
          ports:
          - containerPort: 8080

